name: Manual Trigger

on:
  workflow_dispatch:
    inputs:
      parameter_name:
        description: 'Description of the parameter'
        required: true
        default: 'Default value'

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Run script
      run: |
        echo "Hello, GitHub Actions!"
        echo "Parameter value: ${{ github.event.inputs.parameter_name }}"
        # Add your custom script or commands here
